/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        admin: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          500: '#0284c7',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
        "outline": "#737686",
        "on-primary-fixed": "#00174b",
        "surface-container-high": "#e2e7ff",
        "primary-fixed": "#dbe1ff",
        "surface-container-low": "#f2f3ff",
        "surface-tint": "#0053db",
        "background": "#faf8ff",
        "on-primary-fixed-variant": "#003ea8",
        "surface-container": "#eaedff",
        "surface-variant": "#dae2fd",
        "inverse-primary": "#b4c5ff",
        "on-tertiary-container": "#ffece5",
        "surface-container-highest": "#dae2fd",
        "on-tertiary-fixed-variant": "#783200",
        "on-tertiary": "#ffffff",
        "secondary": "#00687a",
        "secondary-container": "#57dffe",
        "on-surface": "#131b2e",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#006172",
        "primary-container": "#2563eb",
        "tertiary-fixed": "#ffdbca",
        "outline-variant": "#c3c6d7",
        "tertiary": "#8e3c00",
        "inverse-on-surface": "#eef0ff",
        "error": "#ba1a1a",
        "inverse-surface": "#283044",
        "on-background": "#131b2e",
        "error-container": "#ffdad6",
        "secondary-fixed": "#acedff",
        "on-secondary": "#ffffff",
        "surface-bright": "#faf8ff",
        "secondary-fixed-dim": "#4cd7f6",
        "surface": "#faf8ff",
        "on-tertiary-fixed": "#341100",
        "on-primary-container": "#eeefff",
        "tertiary-container": "#b54e00",
        "on-secondary-fixed": "#001f26",
        "tertiary-fixed-dim": "#ffb690",
        "on-error": "#ffffff",
        "surface-dim": "#d2d9f4",
        "primary": "#004ac6",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary": "#ffffff",
        "on-surface-variant": "#434655",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#004e5c"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit-xl": "2rem",
        "unit-3xl": "4rem",
        "unit-md": "1rem",
        "unit-4xl": "6rem",
        "unit-2xs": "0.25rem",
        "gutter-desktop": "1.5rem",
        "unit-lg": "1.5rem",
        "container-max": "80rem",
        "gutter-mobile": "1rem",
        "unit-sm": "0.75rem",
        "unit-2xl": "3rem",
        "unit-xs": "0.5rem"
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "display-hero-mobile": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "title-card": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "price-hero": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "display-hero": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "label-spec": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "price-regular": ["Plus Jakarta Sans", "Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "800" }],
        "title-card": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "price-hero": ["28px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "label-spec": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
        "headline-sm": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "price-regular": ["20px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "700" }]
      },
      keyframes: {
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '15%':      { transform: 'translateX(-8px)' },
          '30%':      { transform: 'translateX(8px)' },
          '45%':      { transform: 'translateX(-6px)' },
          '60%':      { transform: 'translateX(6px)' },
          '75%':      { transform: 'translateX(-3px)' },
          '90%':      { transform: 'translateX(3px)' },
        },
      },
      animation: {
        shake: 'shake 0.5s ease-in-out',
      },
    },
  },
  plugins: [],
}
